CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    blacklisted BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) NOT NULL CHECK (role IN ('USER', 'ADMIN')) DEFAULT 'USER'
);
